### ISSUE TITLE
[Feature Request] Better TypeScript suppport

### ISSUE THREAD

**Issue by cloakedch** [aishek/axios-rate-limit#20]
Dear Alexandr

Thank you for implementing a rate-limiting feature for Axios. It works very well!
If you find some time, maybe you could address some TypeScript-related issues I am facing:

- Export the `RateLimitedAxiosInstance` interface, so that we can have a specific type (instead of `any`) in our projects

- default export axiosRateLimit (instead of `export = axiosRateLimit;`). I had to turn on a compiler option (`esModuleInterop`) to make axios-rate-limit work in modern es6 projects.

Thank you!

EDIT:
I've just seen this pull request: [https://github.com/aishek/axios-rate-limit/pull/19](https://github.com/aishek/axios-rate-limit/pull/19).

It seems like my second suggestion has already been fixed in 1.2.1. However, I still get that problem. What is the correct import statement in TypeScript now?

**Comment by aishek** [comment]
Thanks for kind words!

I still not using Typescript in my everyday work, so will very appreciate any help

**Comment by patarapolw** [comment]
Installed from NPM, but it is still a no.

![Screen Shot 2563-07-25 at 18 25 55](https://user-images.githubusercontent.com/21255931/88455987-496c1580-cea4-11ea-8edc-dcf42349cc1d.png)

**Comment by aishek** [comment]
Fixed in https://www.npmjs.com/package/axios-rate-limit/v/1.3.0

**Comment by qathom** [comment]
Hi @aishek,

Thanks for releasing v1.3.0.
I'm not sure if I'm doing something wrong. I'm still not able to import `axios-rate-limit` **without** enabling `esModuleInterop: true`.

```ts
import * as axiosRateLimit from 'axios-rate-limit';
```

Error:
This expression is not callable.
  Type 'typeof import("node_modules/axios-rate-limit/typings/index")' has no call signatures

Workaround: use ```json{ "esModuleInterop": true }``` in tsconfig.json
